// packages/vue/src/modal/Background.vue
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({});
</script>

<template>
  <div
    class="container"
    :style="{
      'background-color': 'rgba(229, 231, 235)',
      opacity: 0.8,
      ...$attrs.style,
    }"
  />
</template>

<style scoped>
.container {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}
</style>

// packages/solid/src/modal/Background.tsx
import type { Component } from "solid-js"
import { mergeProps } from "solid-js/web";
import { styled } from "solid-styled-components"

type Props = {
  zIndex: number;
	backgroundColor?: string,
	opacity?: number
  onClick: () => any
};

const ModalBackground: Component<Props> = (props) => {
	props = mergeProps({
		backgroundColor: 'rgba(229, 231, 235)',
		opacity :0.8,
  }, props)


	return <Container {...props} />
}

export default ModalBackground

const Container = styled('div')`
	position: fixed;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	z-index: ${props => props.zIndex};
	background-color: ${props => props.backgroundColor};
	opacity: ${props => props.opacity};
`
