// packages/solid/example/App.tsx
import { Component, useContext } from 'solid-js';
import { styled } from 'solid-styled-components';
import { ModalOutlet, setModal } from '../src/modal';
import { ToasterBag, addNotification } from '../src/toaster';
import ExampleNotification from './Notification';

const App: Component = () => {
  return (
    <>
      <ModalOutlet />

      <ToasterBag x="center" />

      <button
        type="button"
        onClick={() => setModal({ Component: ExampleModal, data: {} })}
      >
        open modal
      </button>

      <button
        type="button"
        onClick={() =>
          addNotification(ExampleNotification, { message: 'Test test' })
        }
      >
        open toast
      </button>
    </>
  );
};

export default App;

// const ExampleToast = props => {
//   return <p>{props.context.percentage()}</p>;
// };

const ExampleModal = () => {
  return <ModalContainer>My custom modal</ModalContainer>;
};

const ModalContainer: Component = styled('div')`
  padding: 1rem;
  background-color: white;
`;

// packages/svelte/example/src/App.svelte
<script>
  import {
    ToasterBag,
    addNotification,
    ModalOutlet,
    setModal,
    ModalBackground,
  } from '@guillotin/svelte';
  import Notification from './Notification.svelte';
  import Modal from './Modal.svelte';
</script>

<ToasterBag x="center" y="top" />

<ModalOutlet>
  <div slot="background" let:close>
    <ModalBackground backgroundColor="rgba(147, 197, 253)" {close} />
  </div>
</ModalOutlet>

<main>
  <section>
    <h1>Notification</h1>

    <button
      type="button"
      on:click={() => {
        addNotification(Notification, { message: 'new notification' });
      }}>Add notification</button
    >
  </section>

  <section>
    <h1>Modal</h1>

    <button
      type="button"
      on:click={() => {
        setModal(Modal);
      }}>Open Modal</button
    >
  </section>
</main>
