// packages/vue/src/toaster/ToasterBag.vue
<template>
  <guillotin-toaster-bag ref="el">
    <div slot="content">
      <div v-for="notification in notifications" :key="notification.id">
        <ToasterWrapper :dismiss="() => toasterStore.dismiss(notification.id)">
          <component
            :is="notification.Component"
            v-bind="notification"
            :dismiss="() => toasterStore.dismiss(notification.id)"
          />
        </ToasterWrapper>
      </div>
      <!-- {#each $toasterStore as { Component, id, duration = toasterConstants.DEFAULT_DURATION, animationDuration = toasterConstants.DEFAULT_ANIMATION_DURATION, ...forwardedProps } (id)}
      <ToastWrapper
        dismiss={() => toasterStore.dismiss(id)}
        let:percentage
        {duration}
        {animationDuration}
      >
        <svelte:component
          this={Component}
          {...forwardedProps}
          {percentage}
          dismiss={() => toasterStore.dismiss(id)}
        />
      </ToastWrapper>
    {/each} -->
    </div>
  </guillotin-toaster-bag>
</template>

<script>
import '@guillotin/core';
import { toasterStore } from '@guillotin/core';
import ToasterWrapper from './ToastWrapper.vue';

let initialData = [];

const unsubscribe = toasterStore.subscribe(notifications => {
  initialData = notifications;
});

export default {
  components: { ToasterWrapper },

  // TODO: handle types from core
  mounted() {
    this.$refs.el.x = this.x;
    this.$refs.el.y = this.y;

    this.unsubscribeFn = toasterStore.subscribe(notifications => {
      this.notifications = notifications;
    });
  },

  destroyed() {
    if (!this.unsubscribeFn) return;
    this.unsubscribeFn();
  },

  props: {
    x: {
      type: String,
      default: 'right',
    },
    y: {
      type: String,
      default: 'bottom',
    },
  },

  data() {
    unsubscribe();

    return {
      notifications: initialData,
      unsubscribeFn: null,
    };
  },

  computed: {
    toasterStore() {
      return toasterStore;
    },
  },

  watch: {
    x(val) {
      this.$refs.el.x = val;
    },
    y(val) {
      this.$refs.el.y = val;
    },
  },
};
</script>

// packages/core/src/toaster/ToasterBag.svelte
<svelte:options tag="guillotin-toaster-bag" />

<script context="module">
  export type XPosition = 'right' | 'left' | 'center';
  export type YPosition = 'top' | 'bottom';
</script>

<script>
  // import { DEFAULT_ANIMATION_DURATION, DEFAULT_DURATION } from './constants';
  // import notifications from './store';
  // import ToastWrapper from './ToastWrapper.svelte';

  export let x: XPosition = 'right';
  export let y: YPosition = 'bottom';
</script>

<div class={['bag', x, y].join(' ')}>
  <slot name="content" />
  <!-- {#each $notifications as { Component, id, duration = DEFAULT_DURATION, animationDuration = DEFAULT_ANIMATION_DURATION, ...forwardedProps } (id)}
    <ToastWrapper
      dismiss={() => notifications.dismiss(id)}
      let:percentage
      {duration}
      {animationDuration}
    >
      <svelte:component
        this={Component}
        {...forwardedProps}
        {percentage}
        dismiss={() => notifications.dismiss(id)}
      />
    </ToastWrapper>
  {/each} -->
</div>

<style>
  .bag {
    padding: 1rem;
    position: fixed;
    z-index: 99999;
  }

  .bag.right {
    right: 0;
  }

  .bag.left {
    left: 0;
  }

  .bag.bottom {
    bottom: 0;
  }

  .bag.center {
    left: 50%;
    transform: translateX(-50%);
  }
</style>
